server:
  port: 8081

XServerTopologyBuilder:
  xregistry: ${XREGISTRY_ADDRESS}  # 127.0.0.1:8080

XMessaging:
  NatsAddress: ${NATS_ADDRESS}  # nats://222.201.144.196:4222

Neo4j:
  address: ${NEO4J_ADDRESS} # bolt://localhost:7687